version: "3.8"

services:
  mobil-gmoplus-local:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mobil-gmoplus-local
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=gmoplus_mobil
      - DB_USER=gmoplus_mobiluser
      - DB_PASS=gmoplus_mobiluser1234
      - DB_PREFIX=fl_
      - SITE_URL=http://localhost
      - DEBUG=true
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: mobil-gmoplus-db-local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gmoplus_mobil
      MYSQL_USER: gmoplus_mobiluser
      MYSQL_PASSWORD: gmoplus_mobiluser1234
    volumes:
      - db_data:/var/lib/mysql
      - ./gmoplus_mobil.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  db_data:
